[build]
  publish = "build"
  command = "npm run build"

[dev]
  command = "npm run dev"
  port = 5173          # Port Netlify CLI yumva (proxy port)
  targetPort = 5173    # Port server yawe nyirizina ikoresha

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
